-- Apply migration 011 first. Sample recipes, not verified menus of real businesses.
begin;
do $$
declare owner_uuid uuid;
begin
 select owner_id into owner_uuid from public.restaurants where id='window';
 if owner_uuid is null then raise exception 'Import the original catalog first.'; end if;
 insert into public.restaurants(id,owner_id,name,cuisine,address,hours,photo) values('harvest',owner_uuid,'Harvest Bowl Kitchen','Healthy','Davis, CA · Sample restaurant','10am – 8pm','demo-kitchen') on conflict(id) do nothing;
 insert into public.restaurants(id,owner_id,name,cuisine,address,hours,photo) values('morning',owner_uuid,'Morning Table','Cafe','Sacramento, CA · Sample restaurant','7am – 3pm','window') on conflict(id) do nothing;
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('rice-bowl','demo-kitchen','Chicken Bowl','Bowls',1300,'rice-bowl','[{"name":"Chicken","quantity":1},{"name":"White rice","quantity":1},{"name":"Carrot","quantity":1},{"name":"Zucchini","quantity":1},{"name":"Ginger","quantity":1},{"name":"Olive oil","quantity":1}]'::jsonb,ARRAY[]::text[],'{}'::jsonb,'Grilled chicken over soft rice with ginger-roasted vegetables.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('tomato-soup','demo-kitchen','Greek Salad Bowl','Salads',1150,'tomato-soup','[{"name":"Lettuce","quantity":1},{"name":"Tomato","quantity":1},{"name":"Cucumber","quantity":1},{"name":"Feta","quantity":1},{"name":"Red onion","quantity":1},{"name":"Olive oil","quantity":1},{"name":"Lemon juice","quantity":1}]'::jsonb,ARRAY['dairy','high-fiber','hard-texture']::text[],'{"dairy":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","hard-texture":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Crisp greens and cucumber with feta and a lemon dressing.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('avocado-toast','demo-kitchen','Falafel Pita','Sandwiches',975,'avocado-toast','[{"name":"Wheat pita","quantity":1},{"name":"Chickpeas","quantity":1},{"name":"Parsley","quantity":1},{"name":"Garlic","quantity":1},{"name":"Tahini (sesame)","quantity":1},{"name":"Tomato","quantity":1},{"name":"Lemon juice","quantity":1}]'::jsonb,ARRAY['gluten','sesame','high-fiber']::text[],'{"gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","sesame":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Warm pita filled with chickpea falafel, tahini, and tomatoes.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('seasonal-special','demo-kitchen','Pita Bread','Sides',350,'seasonal-special','[{"name":"Wheat flour","quantity":1},{"name":"Water","quantity":1},{"name":"Yeast","quantity":1},{"name":"Olive oil","quantity":1},{"name":"Salt","quantity":1}]'::jsonb,ARRAY['gluten']::text[],'{"gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'A warm, soft wheat flatbread served on the side.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('window-cupcake','window','Peanut Butter Cupcake','Desserts',600,'cupcake','[{"name":"Wheat flour","quantity":1},{"name":"Peanut butter","quantity":1},{"name":"Milk","quantity":1},{"name":"Egg","quantity":1},{"name":"Sugar","quantity":1},{"name":"Butter","quantity":1},{"name":"Baking powder","quantity":1}]'::jsonb,ARRAY['gluten','peanuts','dairy','eggs']::text[],'{"gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","peanuts":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","dairy":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","eggs":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'A vanilla cupcake with peanut butter frosting and caramel drizzle.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('window-latte','window','Iced Latte','Drinks',600,'latte','[{"name":"Espresso","quantity":1},{"name":"Whole milk","quantity":1},{"name":"Ice","quantity":1}]'::jsonb,ARRAY['dairy']::text[],'{"dairy":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Espresso and chilled whole milk poured over ice.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('window-toast','window','Avocado tomato toast','Sandwiches',600,'toast','[{"name":"Whole-wheat bread","quantity":1},{"name":"Avocado","quantity":1},{"name":"Tomato","quantity":1},{"name":"Red onion","quantity":1},{"name":"Olive oil","quantity":1},{"name":"Basil","quantity":1},{"name":"Lemon juice","quantity":1}]'::jsonb,ARRAY['gluten','high-fiber','hard-texture']::text[],'{"gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","hard-texture":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Avocado and sliced tomato on crisp whole-wheat toast.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('cava-lemon-bowl','demo-kitchen','Lemon Herb Rice Bowl','Bowls',1100,'rice-bowl','[{"name":"White rice","quantity":1},{"name":"Chicken","quantity":1},{"name":"Carrot","quantity":1},{"name":"Olive oil","quantity":1},{"name":"Lemon juice","quantity":1},{"name":"Parsley","quantity":1}]'::jsonb,ARRAY[]::text[],'{}'::jsonb,'A mild chicken and rice bowl with carrots and fresh parsley.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('cava-side-salad','demo-kitchen','Garden Side Salad','Sides',450,'tomato-soup','[{"name":"Lettuce","quantity":1},{"name":"Cucumber","quantity":1},{"name":"Tomato","quantity":1},{"name":"Red onion","quantity":1},{"name":"Olive oil","quantity":1},{"name":"Lemon juice","quantity":1}]'::jsonb,ARRAY['high-fiber','hard-texture']::text[],'{"high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","hard-texture":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'A small crunchy salad with a light lemon dressing.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('luigino-bruschetta','luigino','Tomato Avocado Bruschetta','Sandwiches',1050,'toast','[{"name":"Sourdough wheat bread","quantity":1},{"name":"Tomato","quantity":1},{"name":"Avocado","quantity":1},{"name":"Basil","quantity":1},{"name":"Garlic","quantity":1},{"name":"Olive oil","quantity":1}]'::jsonb,ARRAY['gluten','high-fiber','hard-texture']::text[],'{"gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","hard-texture":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Toasted sourdough topped with ripe tomato, avocado, and basil.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('luigino-chicken','luigino','Herbed Chicken and Rice','Mains',1550,'rice-bowl','[{"name":"Chicken","quantity":1},{"name":"White rice","quantity":1},{"name":"Carrot","quantity":1},{"name":"Zucchini","quantity":1},{"name":"Rosemary","quantity":1},{"name":"Olive oil","quantity":1}]'::jsonb,ARRAY[]::text[],'{}'::jsonb,'Rosemary chicken served with rice and roasted vegetables.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('luigino-salad','luigino','Italian Garden Salad','Salads',1150,'tomato-soup','[{"name":"Lettuce","quantity":1},{"name":"Tomato","quantity":1},{"name":"Cucumber","quantity":1},{"name":"Parmesan","quantity":1},{"name":"Red onion","quantity":1},{"name":"Olive oil","quantity":1},{"name":"Red wine vinegar","quantity":1}]'::jsonb,ARRAY['dairy','high-fiber','hard-texture']::text[],'{"dairy":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","hard-texture":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Garden vegetables with shaved parmesan and a vinegar dressing.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('luigino-bread','luigino','Warm Flatbread','Sides',400,'seasonal-special','[{"name":"Wheat flour","quantity":1},{"name":"Water","quantity":1},{"name":"Yeast","quantity":1},{"name":"Olive oil","quantity":1},{"name":"Salt","quantity":1}]'::jsonb,ARRAY['gluten']::text[],'{"gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Soft house-style flatbread with olive oil.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('sokyo-chicken','sokyo','Ginger Chicken Rice Bowl','Bowls',1450,'rice-bowl','[{"name":"Chicken","quantity":1},{"name":"White rice","quantity":1},{"name":"Carrot","quantity":1},{"name":"Ginger","quantity":1},{"name":"Soy sauce (soy, wheat)","quantity":1},{"name":"Sesame oil","quantity":1},{"name":"Spring onion","quantity":1}]'::jsonb,ARRAY['soy','gluten','sesame','high-sodium']::text[],'{"soy":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","sesame":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","high-sodium":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Ginger chicken and vegetables with a soy-sesame dressing.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('sokyo-mild-chicken','sokyo','Steamed Chicken Rice Bowl','Bowls',1350,'rice-bowl','[{"name":"Chicken","quantity":1},{"name":"White rice","quantity":1},{"name":"Carrot","quantity":1},{"name":"Ginger","quantity":1},{"name":"Water","quantity":1}]'::jsonb,ARRAY[]::text[],'{}'::jsonb,'A simply prepared bowl of steamed chicken, rice, and soft carrots.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('sokyo-salad','sokyo','Sesame Garden Salad','Salads',950,'tomato-soup','[{"name":"Lettuce","quantity":1},{"name":"Cucumber","quantity":1},{"name":"Tomato","quantity":1},{"name":"Sesame seeds","quantity":1},{"name":"Rice vinegar","quantity":1},{"name":"Soy sauce (soy, wheat)","quantity":1}]'::jsonb,ARRAY['sesame','soy','gluten','high-fiber','hard-texture','high-sodium']::text[],'{"sesame":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","soy":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","hard-texture":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","high-sodium":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Crisp vegetables with toasted sesame and a rice-vinegar dressing.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('window-black-coffee','window','Iced Oat Latte','Drinks',550,'latte','[{"name":"Espresso","quantity":1},{"name":"Certified gluten-free oat milk","quantity":1},{"name":"Ice","quantity":1}]'::jsonb,ARRAY[]::text[],'{}'::jsonb,'An iced espresso drink made with oat milk.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('harvest-chicken','harvest','Roasted Chicken Bowl','Bowls',1450,'rice-bowl','[{"name":"Chicken","quantity":1},{"name":"Brown rice","quantity":1},{"name":"Carrot","quantity":1},{"name":"Zucchini","quantity":1},{"name":"Olive oil","quantity":1},{"name":"Parsley","quantity":1}]'::jsonb,ARRAY['high-fiber']::text[],'{"high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Roasted chicken and vegetables over brown rice.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('harvest-salad','harvest','Crunchy Garden Bowl','Salads',1200,'tomato-soup','[{"name":"Lettuce","quantity":1},{"name":"Tomato","quantity":1},{"name":"Cucumber","quantity":1},{"name":"Red onion","quantity":1},{"name":"Sunflower seeds","quantity":1},{"name":"Olive oil","quantity":1},{"name":"Lemon juice","quantity":1}]'::jsonb,ARRAY['high-fiber','hard-texture']::text[],'{"high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","hard-texture":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Colorful vegetables with sunflower seeds and lemon dressing.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('harvest-pita','harvest','Chickpea Pita','Sandwiches',1100,'avocado-toast','[{"name":"Wheat pita","quantity":1},{"name":"Chickpeas","quantity":1},{"name":"Tahini (sesame)","quantity":1},{"name":"Parsley","quantity":1},{"name":"Tomato","quantity":1},{"name":"Lemon juice","quantity":1}]'::jsonb,ARRAY['gluten','sesame','high-fiber']::text[],'{"gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","sesame":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Chickpeas and tahini tucked into a wheat pita with fresh tomato.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('harvest-soft-bowl','harvest','Soft Chicken and Rice','Bowls',1250,'rice-bowl','[{"name":"Poached chicken","quantity":1},{"name":"White rice","quantity":1},{"name":"Cooked carrot","quantity":1},{"name":"Olive oil","quantity":1},{"name":"Water","quantity":1}]'::jsonb,ARRAY[]::text[],'{}'::jsonb,'Tender chicken and well-cooked rice with soft carrots.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('morning-toast','morning','Avocado Breakfast Toast','Sandwiches',1050,'toast','[{"name":"Whole-wheat bread","quantity":1},{"name":"Avocado","quantity":1},{"name":"Tomato","quantity":1},{"name":"Red onion","quantity":1},{"name":"Basil","quantity":1},{"name":"Olive oil","quantity":1}]'::jsonb,ARRAY['gluten','high-fiber','hard-texture']::text[],'{"gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","high-fiber":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","hard-texture":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Toasted bread with creamy avocado and fresh tomato.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('morning-latte','morning','Iced Vanilla Latte','Drinks',550,'latte','[{"name":"Espresso","quantity":1},{"name":"Whole milk","quantity":1},{"name":"Vanilla syrup","quantity":1},{"name":"Ice","quantity":1}]'::jsonb,ARRAY['dairy']::text[],'{"dairy":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'Chilled espresso and milk lightly sweetened with vanilla.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('morning-cupcake','morning','Peanut Butter Cupcake','Desserts',550,'cupcake','[{"name":"Wheat flour","quantity":1},{"name":"Peanut butter","quantity":1},{"name":"Milk","quantity":1},{"name":"Egg","quantity":1},{"name":"Butter","quantity":1},{"name":"Sugar","quantity":1},{"name":"Caramel","quantity":1}]'::jsonb,ARRAY['gluten','peanuts','dairy','eggs']::text[],'{"gluten":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","peanuts":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","dairy":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff.","eggs":"Listed for this sample recipe; confirm preparation and ingredient substitutions with staff."}'::jsonb,'A small cupcake topped with peanut butter and caramel.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 insert into public.dishes(id,restaurant_id,name,category,price_cents,photo,ingredients,flags,flag_notes,description,complete)
 values('morning-oat-latte','morning','Iced Oat Latte','Drinks',600,'latte','[{"name":"Espresso","quantity":1},{"name":"Certified gluten-free oat milk","quantity":1},{"name":"Ice","quantity":1}]'::jsonb,ARRAY[]::text[],'{}'::jsonb,'Espresso over ice with creamy oat milk.',true)
 on conflict(id) do update set category=excluded.category, ingredients=excluded.ingredients, flags=excluded.flags, flag_notes=excluded.flag_notes, description=excluded.description, complete=excluded.complete
 where public.dishes.restaurant_id=excluded.restaurant_id and (select r.version=1 from public.restaurants r where r.id=excluded.restaurant_id);
 update public.restaurants set cuisine='Mediterranean' where id='demo-kitchen' and cuisine='Mediterranean · Greek inspired';
 update public.restaurants set cuisine='Cafe' where id='window' and cuisine in ('Café','Cafe · Coffee · Deli-style');
 update public.dishes set category=case id when 'rice-bowl' then 'Bowls' when 'tomato-soup' then 'Salads' when 'avocado-toast' then 'Sandwiches' when 'seasonal-special' then 'Sides' when 'window-cupcake' then 'Desserts' when 'window-latte' then 'Drinks' when 'window-toast' then 'Sandwiches' end where category='Mains' and id in ('rice-bowl','tomato-soup','avocado-toast','seasonal-special','window-cupcake','window-latte','window-toast');
end $$;
commit;
